title: Alyxandra Palumbo
logo: assets/img/IMG_4183 copy.png
description: Hello there - great to meet you! Reach out to me at alyxrichelle@gmail.com for any and all inquiries.
show downloads: true
theme: jekyll-theme-minimal
